import base64
import requests
from message_bus import MessageBus
from llm_client import call_llm
from config import GITHUB_TOKEN, GITHUB_REPO

GITHUB_HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}
BRANCH_NAME = "agent-landing-page"

HTML_SYSTEM_PROMPT = """You are a frontend developer. Generate a complete, working HTML landing page for a startup.

Include:
- A compelling headline (the product name)
- A subheadline (the value proposition)
- A features section listing all features
- A call-to-action button ("Get Early Access")
- Inline CSS styling (modern, clean, professional)

Respond with ONLY the raw HTML. No markdown. No explanation."""

PR_BODY_PROMPT = """Write a GitHub pull request description for a landing page commit.
Mention the product name, what the page includes, and that it was generated by the EngineerAgent.
Keep it under 150 words."""


class EngineerAgent:
    def __init__(self, bus: MessageBus):
        self.bus = bus

    def run(self) -> None:
        messages = self.bus.receive("engineer")
        for msg in messages:
            if msg["message_type"] not in ("task", "revision_request"):
                continue
            print(f"\n[ENGINEER] Processing message type={msg['message_type']}")
            spec = msg["payload"]["product_spec"]
            feedback = msg["payload"].get("feedback", "")

            html = self._generate_html(spec, feedback)
            sha = self._get_main_sha()
            self._create_branch(sha)
            issue_url, issue_number = self._create_github_issue(spec)
            pr_url = self._commit_file_and_open_pr(html, spec, issue_number)

            print(f"[ENGINEER] PR opened: {pr_url}")
            print(f"[ENGINEER] Issue created: {issue_url}")

            self.bus.send(
                from_agent="engineer",
                to_agent="ceo",
                message_type="result",
                payload={
                    "pr_url": pr_url,
                    "issue_url": issue_url,
                    "html_content": html,
                    "branch": BRANCH_NAME,
                },
                parent_message_id=msg["message_id"],
            )

    def _generate_html(self, spec: dict, feedback: str = "") -> str:
        user_prompt = (
            f"Product value proposition: {spec['value_proposition']}\n"
            f"Features: {spec['features']}\n"
            f"Personas: {spec['personas']}\n"
        )
        if feedback:
            user_prompt += f"\nFeedback to address: {feedback}"
        html = call_llm(HTML_SYSTEM_PROMPT, user_prompt, max_tokens=3000)
        if html.strip().startswith("```"):
            html = html.strip().removeprefix("```html").removeprefix("```").removesuffix("```").strip()
        return html

    def _create_github_issue(self, spec: dict) -> tuple[str, int]:
        issue_body = (
            f"## Initial Landing Page\n\n"
            f"**Value Proposition:** {spec['value_proposition']}\n\n"
            f"**Features to showcase:**\n"
            + "\n".join(f"- {f['name']}: {f['description']}" for f in spec["features"])
            + "\n\n_Created by EngineerAgent_"
        )
        r = requests.post(
            f"https://api.github.com/repos/{GITHUB_REPO}/issues",
            headers=GITHUB_HEADERS,
            json={"title": "Initial landing page", "body": issue_body},
        )
        r.raise_for_status()
        data = r.json()
        return data["html_url"], data["number"]

    def _get_main_sha(self) -> str:
        r = requests.get(
            f"https://api.github.com/repos/{GITHUB_REPO}/git/ref/heads/main",
            headers=GITHUB_HEADERS,
        )
        r.raise_for_status()
        return r.json()["object"]["sha"]

    def _create_branch(self, sha: str) -> None:
        # Create branch (422 if already exists — that's fine)
        requests.post(
            f"https://api.github.com/repos/{GITHUB_REPO}/git/refs",
            headers=GITHUB_HEADERS,
            json={"ref": f"refs/heads/{BRANCH_NAME}", "sha": sha},
        )

    def _commit_file_and_open_pr(self, html: str, spec: dict, issue_number: int) -> str:
        # Commit file
        encoded = base64.b64encode(html.encode()).decode()
        requests.put(
            f"https://api.github.com/repos/{GITHUB_REPO}/contents/index.html",
            headers=GITHUB_HEADERS,
            json={
                "message": "feat: add landing page generated by EngineerAgent",
                "content": encoded,
                "branch": BRANCH_NAME,
                "author": {"name": "EngineerAgent", "email": "agent@launchmind.ai"},
            },
        )

        # Open PR
        pr_body = call_llm(
            "You write concise GitHub PR descriptions.",
            f"{PR_BODY_PROMPT}\nProduct: {spec['value_proposition']}\nCloses #{issue_number}",
            max_tokens=200,
        )
        r = requests.post(
            f"https://api.github.com/repos/{GITHUB_REPO}/pulls",
            headers=GITHUB_HEADERS,
            json={
                "title": "Initial landing page",
                "body": pr_body + f"\n\nCloses #{issue_number}",
                "head": BRANCH_NAME,
                "base": "main",
            },
        )
        r.raise_for_status()
        return r.json()["html_url"]
