import base64
import uuid
import requests
from message_bus import MessageBus
from llm_client import call_llm
from config import GITHUB_TOKEN, GITHUB_REPO

GITHUB_HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}
BRANCH_NAME_PREFIX = "agent-landing-page"

HTML_SYSTEM_PROMPT = """You are a frontend developer. Generate a complete, working HTML landing page for a startup.

Include:
- A compelling headline (the product name)
- A subheadline (the value proposition)
- A features section listing all features
- A call-to-action button ("Get Early Access")
- Inline CSS styling (modern, clean, professional)

Respond with ONLY the raw HTML. No markdown. No explanation."""

PR_BODY_PROMPT = """Write a GitHub pull request description for a landing page commit.
Mention the product name, what the page includes, and that it was generated by the EngineerAgent.
Keep it under 150 words."""


class EngineerAgent:
    def __init__(self, bus: MessageBus):
        self.bus = bus

    def run(self) -> None:
        messages = self.bus.receive("engineer")
        for msg in messages:
            if msg["message_type"] not in ("task", "revision_request"):
                continue
            print(f"\n[ENGINEER] Processing message type={msg['message_type']}")
            spec = msg["payload"]["product_spec"]
            feedback = msg["payload"].get("feedback", "")
            branch_name = f"{BRANCH_NAME_PREFIX}-{uuid.uuid4().hex[:8]}"

            html = self._generate_html(spec, feedback)
            base_branch, sha = self._get_base_branch_and_sha()
            self._create_branch(branch_name, sha)
            issue_url, issue_number = self._create_github_issue(spec)
            pr_url = self._commit_file_and_open_pr(
                html,
                spec,
                issue_number,
                base_branch,
                branch_name,
            )

            print(f"[ENGINEER] PR opened: {pr_url}")
            print(f"[ENGINEER] Issue created: {issue_url}")

            self.bus.send(
                from_agent="engineer",
                to_agent="ceo",
                message_type="result",
                payload={
                    "pr_url": pr_url,
                    "issue_url": issue_url,
                    "html_content": html,
                    "branch": branch_name,
                },
                parent_message_id=msg["message_id"],
            )

    def _generate_html(self, spec: dict, feedback: str = "") -> str:
        user_prompt = (
            f"Product value proposition: {spec['value_proposition']}\n"
            f"Features: {spec['features']}\n"
            f"Personas: {spec['personas']}\n"
        )
        if feedback:
            user_prompt += f"\nFeedback to address: {feedback}"
        html = call_llm(HTML_SYSTEM_PROMPT, user_prompt, max_tokens=3000)
        if html.strip().startswith("```"):
            html = html.strip().removeprefix("```html").removeprefix("```").removesuffix("```").strip()
        return html

    def _create_github_issue(self, spec: dict) -> tuple[str, int]:
        issue_body = (
            f"## Initial Landing Page\n\n"
            f"**Value Proposition:** {spec['value_proposition']}\n\n"
            f"**Features to showcase:**\n"
            + "\n".join(f"- {f['name']}: {f['description']}" for f in spec["features"])
            + "\n\n_Created by EngineerAgent_"
        )
        r = requests.post(
            f"https://api.github.com/repos/{GITHUB_REPO}/issues",
            headers=GITHUB_HEADERS,
            json={"title": "Initial landing page", "body": issue_body},
        )
        r.raise_for_status()
        data = r.json()
        return data["html_url"], data["number"]

    def _get_base_branch_and_sha(self) -> tuple[str, str]:
        repo_resp = requests.get(
            f"https://api.github.com/repos/{GITHUB_REPO}",
            headers=GITHUB_HEADERS,
        )
        repo_resp.raise_for_status()
        base_branch = repo_resp.json().get("default_branch", "main")

        ref_resp = requests.get(
            f"https://api.github.com/repos/{GITHUB_REPO}/git/ref/heads/{base_branch}",
            headers=GITHUB_HEADERS,
        )
        if ref_resp.status_code == 409:
            raise RuntimeError(
                "GitHub repository has no commits yet. Create an initial commit on the default branch and retry."
            )
        ref_resp.raise_for_status()
        return base_branch, ref_resp.json()["object"]["sha"]

    def _create_branch(self, branch_name: str, sha: str) -> None:
        # Create branch (422 if already exists — that's fine)
        requests.post(
            f"https://api.github.com/repos/{GITHUB_REPO}/git/refs",
            headers=GITHUB_HEADERS,
            json={"ref": f"refs/heads/{branch_name}", "sha": sha},
        )

    def _get_existing_file_sha(self, branch_name: str, path: str) -> str | None:
        r = requests.get(
            f"https://api.github.com/repos/{GITHUB_REPO}/contents/{path}",
            headers=GITHUB_HEADERS,
            params={"ref": branch_name},
        )
        if r.status_code == 404:
            return None
        r.raise_for_status()
        return r.json().get("sha")

    def _find_existing_open_pr(self, branch_name: str) -> str | None:
        owner = GITHUB_REPO.split("/")[0]
        r = requests.get(
            f"https://api.github.com/repos/{GITHUB_REPO}/pulls",
            headers=GITHUB_HEADERS,
            params={"state": "open", "head": f"{owner}:{branch_name}"},
        )
        r.raise_for_status()
        prs = r.json()
        return prs[0]["html_url"] if prs else None

    def _commit_file_and_open_pr(
        self,
        html: str,
        spec: dict,
        issue_number: int,
        base_branch: str,
        branch_name: str,
    ) -> str:
        # Commit file
        encoded = base64.b64encode(html.encode()).decode()
        existing_sha = self._get_existing_file_sha(branch_name, "index.html")
        payload = {
            "message": "feat: add landing page generated by EngineerAgent",
            "content": encoded,
            "branch": branch_name,
            "author": {"name": "EngineerAgent", "email": "agent@launchmind.ai"},
        }
        if existing_sha:
            payload["sha"] = existing_sha

        put_resp = requests.put(
            f"https://api.github.com/repos/{GITHUB_REPO}/contents/index.html",
            headers=GITHUB_HEADERS,
            json=payload,
        )
        put_resp.raise_for_status()

        # Open PR
        pr_body = call_llm(
            "You write concise GitHub PR descriptions.",
            f"{PR_BODY_PROMPT}\nProduct: {spec['value_proposition']}\nCloses #{issue_number}",
            max_tokens=200,
        )
        r = requests.post(
            f"https://api.github.com/repos/{GITHUB_REPO}/pulls",
            headers=GITHUB_HEADERS,
            json={
                "title": "Initial landing page",
                "body": pr_body + f"\n\nCloses #{issue_number}",
                "head": branch_name,
                "base": base_branch,
            },
        )
        if r.status_code == 422:
            existing_pr_url = self._find_existing_open_pr(branch_name)
            if existing_pr_url:
                return existing_pr_url
        r.raise_for_status()
        return r.json()["html_url"]
